name: Build and Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'v*'  # 当推送v开头的tag时触发

jobs:
  build:
    name: Build Project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ubuntu 构建步骤
      - name: Install Ubuntu Dependencies
        if: startsWith(matrix.os, 'ubuntu-') 
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for Ubuntu
        if: startsWith(matrix.os, 'ubuntu-') 
        run: |
          CROSS_NO_WARNINGS=0 cross build --target i686-unknown-linux-musl --release
          CROSS_NO_WARNINGS=0 cross build --target x86_64-unknown-linux-musl --release
          CROSS_NO_WARNINGS=0 cross build --target aarch64-linux-android --release
          CROSS_NO_WARNINGS=0 cross build --target aarch64-unknown-linux-musl --release

      # Windows 构建步骤
      - name: Build for Windows
        if: startsWith(matrix.os, 'windows-') 
        run: |
          $ENV:RUSTFLAGS='-C target-feature=+crt-static'
          rustup target add i686-pc-windows-msvc
          rustup target add x86_64-pc-windows-msvc
          cargo build --release --target i686-pc-windows-msvc
          cargo build --release --target x86_64-pc-windows-msvc
        shell: pwsh

      # 准备发布文件
      - name: Prepare Release Files
        run: |
          mkdir -p Release
          if [[ "${{ matrix.os }}" == ubuntu* ]]; then
            cp target/x86_64-unknown-linux-musl/release/a2silk-cli Release/a2silk-cli_linux_x86_64
            cp target/aarch64-linux-android/release/a2silk-cli Release/a2silk-cli_android_aarch64
            cp target/aarch64-unknown-linux-musl/release/a2silk-cli Release/a2silk-cli_linux_aarch64
            cp target/i686-unknown-linux-musl/release/a2silk-cli Release/a2silk-cli_linux_i686
          else
            cp target/i686-pc-windows-msvc/release/a2silk-cli.exe Release/a2silk-cli_windows_i686.exe
            cp target/x86_64-pc-windows-msvc/release/a2silk-cli.exe Release/a2silk-cli_windows_x86_64.exe
          fi

      # 上传所有文件为一个Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: Release/
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-binaries
          path: Release/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release containing:
            - Linux (x86_64, i686, aarch64)
            - Android (aarch64)
            - Windows (x86_64, i686)
          draft: false
          prerelease: false
          files: |
            Release/a2silk-cli_linux_x86_64
            Release/a2silk-cli_linux_i686
            Release/a2silk-cli_linux_aarch64
            Release/a2silk-cli_android_aarch64
            Release/a2silk-cli_windows_x86_64.exe
            Release/a2silk-cli_windows_i686.exe
