name: Linux Build and Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'v*'  # 当推送v开头的tag时触发

jobs:
  build:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Linux targets
        run: |
          CROSS_NO_WARNINGS=0 cross build --target i686-unknown-linux-musl --release
          CROSS_NO_WARNINGS=0 cross build --target x86_64-unknown-linux-musl --release
          CROSS_NO_WARNINGS=0 cross build --target aarch64-unknown-linux-musl --release

      - name: Prepare release files
        run: |
          mkdir -p Release
          cp target/x86_64-unknown-linux-musl/release/a2silk-cli Release/a2silk-cli_linux_x86_64
          cp target/aarch64-unknown-linux-musl/release/a2silk-cli Release/a2silk-cli_linux_aarch64
          cp target/i686-unknown-linux-musl/release/a2silk-cli Release/a2silk-cli_linux_i686

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: Release/
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries
          path: Release/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Linux Release ${{ github.ref_name }}
          body: |
            Linux binaries for:
            - x86_64
            - i686
            - aarch64
          files: |
            Release/a2silk-cli_linux_x86_64
            Release/a2silk-cli_linux_i686
            Release/a2silk-cli_linux_aarch64
